// Mock data for Afro AI language learning app

export const AFRICAN_LANGUAGES = [
  {
    id: 'yoruba',
    name: 'Yoruba',
    nativeName: 'Èdè Yorùbá',
    nativeExample: 'Ẹ kú àárọ̀',
    flag: '🇳🇬',
    region: 'Nigeria',
    speakers: '45M+',
  },
  {
    id: 'swahili',
    name: 'Swahili',
    nativeName: 'Kiswahili',
    nativeExample: 'Habari za asubuhi',
    flag: '🇹🇿',
    region: 'East Africa',
    speakers: '100M+',
  },
  {
    id: 'hausa',
    name: 'Hausa',
    nativeName: 'Harshen Hausa',
    nativeExample: 'Ina kwana',
    flag: '🇳🇬',
    region: 'West Africa',
    speakers: '70M+',
  },
  {
    id: 'zulu',
    name: 'Zulu',
    nativeName: 'isiZulu',
    nativeExample: 'Sawubona',
    flag: '🇿🇦',
    region: 'South Africa',
    speakers: '12M+',
  },
  {
    id: 'amharic',
    name: 'Amharic',
    nativeName: 'አማርኛ',
    nativeExample: 'ጤና ይስጥልኝ',
    flag: '🇪🇹',
    region: 'Ethiopia',
    speakers: '32M+',
  },
  {
    id: 'igbo',
    name: 'Igbo',
    nativeName: 'Asụsụ Igbo',
    nativeExample: 'Ụtụtụ ọma',
    flag: '🇳🇬',
    region: 'Nigeria',
    speakers: '45M+',
  },
  {
    id: 'xhosa',
    name: 'Xhosa',
    nativeName: 'isiXhosa',
    nativeExample: 'Molo',
    flag: '🇿🇦',
    region: 'South Africa',
    speakers: '8M+',
  },
  {
    id: 'akan',
    name: 'Akan',
    nativeName: 'Akan',
    nativeExample: 'Maakye',
    flag: '🇬🇭',
    region: 'Ghana',
    speakers: '11M+',
  },
];

export const AI_PERSONALITIES = [
  {
    id: 'quirky',
    name: 'Quirky & Fun',
    emoji: '🎉',
    description: 'Learning with jokes and playful banter',
    color: '#FF6B9D',
  },
  {
    id: 'professional',
    name: 'Serious & Professional',
    emoji: '📚',
    description: 'Structured lessons with clear explanations',
    color: '#4A90D9',
  },
  {
    id: 'friendly',
    name: 'Friendly & Casual',
    emoji: '😊',
    description: 'Like chatting with a supportive friend',
    color: '#7ED321',
  },
  {
    id: 'patient',
    name: 'Patient & Encouraging',
    emoji: '🌟',
    description: 'Gentle pace with lots of positive reinforcement',
    color: '#F5A623',
  },
  {
    id: 'humorous',
    name: 'Humorous',
    emoji: '😄',
    description: 'Comedy-filled learning adventure',
    color: '#BD10E0',
  },
];

export const CULTURAL_TIPS_YORUBA = [
  {
    id: 1,
    tip: "💡 In Yoruba, it's more common to say 'E ku aro' than 'Aro' alone for good morning - the 'E' shows respect!",
    type: 'grammar',
  },
  {
    id: 2,
    tip: "📚 Adding 'o' at the end of greetings shows respect to elders. Example: 'E káàbọ̀ o!'",
    type: 'culture',
  },
  {
    id: 3,
    tip: "🎵 Yoruba is a tonal language - the same word can mean different things based on tone!",
    type: 'pronunciation',
  },
  {
    id: 4,
    tip: "🤝 When greeting elders, it's customary to slightly bow or kneel in Yoruba culture.",
    type: 'culture',
  },
  {
    id: 5,
    tip: "💬 'Ẹ ṣé' means 'thank you' but 'Ẹ ṣé púpọ̀' means 'thank you very much'!",
    type: 'vocabulary',
  },
  {
    id: 6,
    tip: "🌍 Over 45 million people speak Yoruba, making it one of Africa's major languages!",
    type: 'fun_fact',
  },
  {
    id: 7,
    tip: "👋 'Báwo ni' is informal. For elders, use 'Ẹ ká àárọ̀' (Good morning) or 'Ẹ kú ọ̀sán' (Good afternoon).",
    type: 'grammar',
  },
  {
    id: 8,
    tip: "🎭 Yoruba proverbs (Òwe) are highly valued and often used in daily conversation.",
    type: 'culture',
  },
  {
    id: 9,
    tip: "📝 The letters ẹ, ọ, and ṣ are unique to Yoruba. They represent different sounds!",
    type: 'alphabet',
  },
  {
    id: 10,
    tip: "🌅 'Mo dúpẹ́' literally means 'I bow in gratitude' - showing the depth of Yoruba gratitude!",
    type: 'vocabulary',
  },
];

export const VOCABULARY_DATA = [
  {
    id: 1,
    word: 'Báwo ni',
    translation: 'How are you?',
    pronunciation: 'bah-woh nee',
    language: 'yoruba',
    learnedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    isFavorite: true,
  },
  {
    id: 2,
    word: 'Mo wà dáadáa',
    translation: "I'm fine",
    pronunciation: 'moh wah dah-dah-ah',
    language: 'yoruba',
    learnedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    isFavorite: false,
  },
  {
    id: 3,
    word: 'Ẹ ṣé',
    translation: 'Thank you',
    pronunciation: 'eh sheh',
    language: 'yoruba',
    learnedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    isFavorite: true,
  },
  {
    id: 4,
    word: 'Ẹ kú àárọ̀',
    translation: 'Good morning',
    pronunciation: 'eh koo ah-roh',
    language: 'yoruba',
    learnedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    isFavorite: false,
  },
  {
    id: 5,
    word: 'Ẹ kú ọ̀sán',
    translation: 'Good afternoon',
    pronunciation: 'eh koo oh-san',
    language: 'yoruba',
    learnedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    isFavorite: false,
  },
  {
    id: 6,
    word: 'Ẹ kú alẹ́',
    translation: 'Good evening',
    pronunciation: 'eh koo ah-leh',
    language: 'yoruba',
    learnedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
    isFavorite: true,
  },
  {
    id: 7,
    word: 'O dàbọ̀',
    translation: 'Goodbye',
    pronunciation: 'oh dah-boh',
    language: 'yoruba',
    learnedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    isFavorite: false,
  },
  {
    id: 8,
    word: 'Bẹ́ẹ̀ ni',
    translation: 'Yes',
    pronunciation: 'beh-eh nee',
    language: 'yoruba',
    learnedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000),
    isFavorite: false,
  },
  {
    id: 9,
    word: 'Rárá',
    translation: 'No',
    pronunciation: 'rah-rah',
    language: 'yoruba',
    learnedAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000),
    isFavorite: true,
  },
  {
    id: 10,
    word: 'Jọ̀wọ́',
    translation: 'Please',
    pronunciation: 'joh-woh',
    language: 'yoruba',
    learnedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    isFavorite: false,
  },
  {
    id: 11,
    word: 'Orúkọ mi ni...',
    translation: 'My name is...',
    pronunciation: 'oh-roo-koh mee nee',
    language: 'yoruba',
    learnedAt: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000),
    isFavorite: true,
  },
  {
    id: 12,
    word: 'Ọmọ',
    translation: 'Child',
    pronunciation: 'oh-moh',
    language: 'yoruba',
    learnedAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000),
    isFavorite: false,
  },
  {
    id: 13,
    word: 'Omi',
    translation: 'Water',
    pronunciation: 'oh-mee',
    language: 'yoruba',
    learnedAt: new Date(Date.now() - 13 * 24 * 60 * 60 * 1000),
    isFavorite: false,
  },
  {
    id: 14,
    word: 'Oúnjẹ',
    translation: 'Food',
    pronunciation: 'oh-oon-jeh',
    language: 'yoruba',
    learnedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000),
    isFavorite: true,
  },
  {
    id: 15,
    word: 'Ilé',
    translation: 'House/Home',
    pronunciation: 'ee-leh',
    language: 'yoruba',
    learnedAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000),
    isFavorite: false,
  },
  {
    id: 16,
    word: 'Àwọn',
    translation: 'They/Them',
    pronunciation: 'ah-won',
    language: 'yoruba',
    learnedAt: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000),
    isFavorite: false,
  },
  {
    id: 17,
    word: 'Ẹ̀yin',
    translation: 'You (plural/respectful)',
    pronunciation: 'eh-yin',
    language: 'yoruba',
    learnedAt: new Date(Date.now() - 17 * 24 * 60 * 60 * 1000),
    isFavorite: false,
  },
  {
    id: 18,
    word: 'Ìfẹ́',
    translation: 'Love',
    pronunciation: 'ee-feh',
    language: 'yoruba',
    learnedAt: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000),
    isFavorite: true,
  },
  {
    id: 19,
    word: 'Ọ̀rẹ́',
    translation: 'Friend',
    pronunciation: 'oh-reh',
    language: 'yoruba',
    learnedAt: new Date(Date.now() - 19 * 24 * 60 * 60 * 1000),
    isFavorite: true,
  },
  {
    id: 20,
    word: 'Ẹ kú iṣẹ́',
    translation: 'Well done (for working)',
    pronunciation: 'eh koo ee-sheh',
    language: 'yoruba',
    learnedAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000),
    isFavorite: false,
  },
];

export const CONVERSATION_HISTORY = [
  {
    id: 1,
    language: 'yoruba',
    languageName: 'Yoruba',
    flag: '🇳🇬',
    date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    duration: '12 min',
    turns: 24,
    preview: 'Practiced greetings and introductions...',
  },
  {
    id: 2,
    language: 'yoruba',
    languageName: 'Yoruba',
    flag: '🇳🇬',
    date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    duration: '8 min',
    turns: 16,
    preview: 'Learned numbers 1-10 in Yoruba...',
  },
  {
    id: 3,
    language: 'swahili',
    languageName: 'Swahili',
    flag: '🇹🇿',
    date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    duration: '15 min',
    turns: 30,
    preview: 'Basic phrases and travel vocabulary...',
  },
  {
    id: 4,
    language: 'hausa',
    languageName: 'Hausa',
    flag: '🇳🇬',
    date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    duration: '10 min',
    turns: 20,
    preview: 'Introductory lesson with greetings...',
  },
  {
    id: 5,
    language: 'yoruba',
    languageName: 'Yoruba',
    flag: '🇳🇬',
    date: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    duration: '20 min',
    turns: 42,
    preview: 'Advanced conversation about family...',
  },
];

export const SUGGESTED_RESPONSES = [
  {
    id: 1,
    original: 'Mo wà dáadáa, ẹ ṣé',
    translation: "I'm fine, thank you",
  },
  {
    id: 2,
    original: 'Báwo ni ara yín?',
    translation: 'How are you feeling?',
  },
  {
    id: 3,
    original: 'Ẹ jọ̀wọ́, ṣe é lè ràn mí lọ́wọ́?',
    translation: 'Please, can you help me?',
  },
];

export const ONBOARDING_SLIDES = [
  {
    id: 1,
    title: 'Speak Naturally',
    subtitle: 'Speak naturally with AI in 8+ African languages',
    icon: 'chatbubbles',
    color: '#FF6B35',
  },
  {
    id: 2,
    title: 'Cultural Immersion',
    subtitle: 'Get cultural tips as you learn',
    icon: 'earth',
    color: '#4CAF50',
  },
  {
    id: 3,
    title: 'Track Progress',
    subtitle: 'Track your vocabulary progress',
    icon: 'trending-up',
    color: '#2196F3',
  },
];


